### ISSUE TITLE
Thank You Thank You Thank You a Question; Perhaps an issue; Perhaps not

### ISSUE THREAD

**Issue by fuzzygroup** [rocketjob/rails_semantic_logger#19]
Hi, 

1.  thank you.  I nearly wept when I saw this.  Its already made my life easier.
2. I'm dealing with a new app using action cable and the level of cruft that action cable introduces into logs makes me want to weep.  
3. My thinking was that per controller log files would give me the ability to deal with action cable or not but I don't see a clear way to implement that using rails_semantic_logger.  I've looked into appenders but dropping one at the start of a controller(SemanticLogger.add_appender(file_name: 'api_controller.log')  just creates a file; it doesn't put anything there.  Do I need to work at the Rack level if I wanted the output of semantic logger to end up at its own log file?  I don't yet know how closely you work with rack (or not).

Thanks again.
Scott

**Comment by fuzzygroup** [comment]
I need to research this more before I bother you.  Sorry.

**Comment by reidmorrison** [comment]
Rails semantic logger is a global logging system where all logging goes to a central logger. 

A great way to reduce noise is to add a filter to the file logger appender that excludes any controllers of your choice, or a combination of controller and/or message.

Raising the log level on a per controller/class basis is another way to quiet down a noisy module.

If you have an example of the log output you want to reduce after adding rails semantic logger, add it here and re-open this issue. Then we can work together to remove the noise.

Keep in mind that if it annoys you, it very likely annoys a lot of other people too.

**Comment by xanview** [comment]
Quick question, how do I add a filter in rails_semantic_logger? - I found http://rocketjob.github.io/semantic_logger/filtering.html - but what do I put in my production.rb file exactly?

Something like this? <
```ruby
config.rails_semantic_logger.filter = Proc.new {|log| log.message !~ /\A\*\*\* Checking/ }
```

**Comment by reidmorrison** [comment]
The above example is a great idea. Added a commit to master to add this exact feature, so if you can point to github master it should work with your example above.

For now this only affects the File output appender. Most production implementations run with the `--quiet` switch so that stdout logging is disabled in production. 

I.e. The above change will not affect the stdout logger, there are other ways to modify the additional stdout logger. Maybe there is a way to make the stdout logger configurable: https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/rails/server.rb#L8

Without using the latest code from master, this temporary workaround can be used to set the filter in a rails initializer. For example: `config/initializers/semantic_logger.rb`:
~~~ruby
Rails.application.config.after_initialize do
  if Rails.env.production?
    SemanticLogger.appenders.first.filter = Proc.new {|log| log.message !~ /\A\*\*\* Checking/ }
  end
end
~~~

**Comment by xanview** [comment]
Wow, that's fantastic, thank you for implementing this so quickly :)
