### ISSUE TITLE
Change formatter to json

### ISSUE THREAD

**Issue by mhenrixon** [rocketjob/rails_semantic_logger#20]
I've been looking at the code for a really long time now and I can't seem to find any decent way of turning the rails appender into a JSON formatted STDOUT. 

If this isn't easily achievable I wanted to add a feature request for this. I don't like the initializer approach because I am trying to solve a problem once for all our projects which means I am wrapping SemanticLogger (and rails_semantic_logger) in a gem that we own and control that has (for us) sensible defaults.

**Comment by reidmorrison** [comment]
Just added documentation for this scenario under the section titled "Disable default Rails file logging": http://rocketjob.github.io/semantic_logger/rails.html
Let us know if the updated docs properly address this use case, or if you have any other feedback.

To address the common defaults we have a "Common" Rails engine that includes all of our common gem dependencies, defaults, configs and initializers. The Common engine / gem is then added to all our Rails apps so that we are sure they are all consistent.
