### ISSUE TITLE
Support for delayed_job?

### ISSUE THREAD

**Issue by ervoiox** [rocketjob/rails_semantic_logger#28]
Hi,

What would be the recommended configuration to replace the delayed_job logger?

**Comment by reidmorrison** [comment]
Were you able to replace the DelayedJob logger?

If so, please paste the details here, or submit a pull request.

Otherwise consider posting the question in the gitter support channel to see if anyone else using DelayedJob has replaced its logger.

[RocketJob](http://rocketjob.io) is a scalable alternative to DelayedJob which has complete support for Semantic Logger, along with tagging, performance measurements, etc.

**Comment by reidmorrison** [comment]
@ervoiox did the above solution work for Delayed Job?
If so I will add it to Rails Semantic Logger.

**Comment by reidmorrison** [comment]
Please re-open this ticket when you have feedback on the above solution.
