### ISSUE TITLE
ActionView extension is not included in production

### ISSUE THREAD

**Issue by maxim** [rocketjob/rails_semantic_logger#50]
### Environment

* Ruby 2.3.2p217
* Rails 4.2.0
* Semantic Logger 4.2.0
* Rails Semantic Logger 4.1.3
* Puma 3.11.0
* Rails configuration:

    ```ruby
    # config/environments/production.rb
    # …
    config.log_level = :info
    config.rails_semantic_logger.add_file_appender = false
    config.semantic_logger.add_appender(io: STDOUT, formatter: :color, async: true)
    # …
    ```

### Expected Behavior

Logs of "rendered" activity (for views and partials) from ActionView should be classified as `debug`.

### Actual Behavior

In production "rendered" entries are showing up with `I` (info).

What's interesting is that this works fine in development environment. I see "rendered" messages correctly showing up as `D` (debug) and not `I`. I have a hunch that the problem is here:

https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L240

The `defined?(ActionView::LogSubscriber)` might be returning false in production and true in development, but why would it do that? Here's puma config:

```
daemonize false
directory '/app'
threads 1, 40
bind 'unix:///var/run/puma.sock'
worker_timeout 60
environment ENV['RAILS_ENV']
```

**Comment by maxim** [comment]
@reidmorrison Just to summarize, if I understand [this code](https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/action_view/log_subscriber.rb) correctly, the designed behavior is for any `INFO` call coming from ActionView to be converted to `DEBUG`. Unfortunately, for some weird reason this doesn't happen in production, yet it does happen in development.

**Comment by aburgel** [comment]
I've been running into this issue as well. I think its caused by the strategy of checking for the existence of a class to enable this configuration.

Because of how Rails autoloading works, its possible for `ActionView` to be defined but `ActionView::LogSubscriber` to be undefined at this point in the boot process.

The initializer for `ActionView` occurs after the `initialize_logger` step. But for any given app, there may be some other gem that happens to cause the rest of ActionView to be loaded. That's probably why its working development but not production.

My suggestion would be to change `defined?(ActionView::LogSubscriber)` to `defined?(ActionView)`. That goes for the rest of the `defined?` checks in this initialization block.

**Comment by reidmorrison** [comment]
Looks like a great place to start to find the issue. Once you have tested it out and are sure that changing `ActionView::LogSubscriber` to just `ActionView` works then submit a PR.
